/**
 * Emit assets/models.data.js — the 3D assets as data URLs.
 *
 * WHY THIS EXISTS
 * ---------------
 * A published artifact preview serves a fixed set of file types, and .vrm and
 * .glb are not among them. So a preview of these pages could show the design
 * but never the thing the page is actually about: a real hero moving. "It works
 * locally" is not a preview.
 *
 * .js IS served, so the models ride in as base64 inside a module. hero-card.js
 * consults it before fetching, and falls back to the real files when it is
 * absent - so the pages behave identically whether or not this has been run.
 *
 * NOT A SECOND COPY. Sources are the canonical files under
 * games/hero-moves/assets/, read at build time. The output is generated and
 * gitignored, like any other build artifact. Re-run it when the avatars or the
 * clips change:
 *
 *   node marketing/concepts/build-models.mjs
 *
 * Base64 costs a third more bytes than the binary, which for a preview that
 * would otherwise show nothing is a good trade.
 */
import { readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const HERE = new URL('.', import.meta.url).pathname
const GAME = join(HERE, '..', '..', 'games', 'hero-moves', 'assets')

// published path (what the HTML asks for) -> canonical file on disk
const MODELS = {
  'assets/Crayon_Kid.opt.vrm': join(GAME, 'avatars', 'Crayon_Kid.opt.vrm'),
  'assets/anim/Flying_Forward_Super.glb': join(GAME, 'animations', 'Flying_Forward_Super.glb'),
  'assets/anim/Dance_Charleston.glb': join(GAME, 'animations', 'Dance_Charleston.glb'),
  'assets/anim/Backflip.glb': join(GAME, 'animations', 'Backflip.glb'),
}

const MIME = { '.vrm': 'model/gltf-binary', '.glb': 'model/gltf-binary' }

const entries = []
let raw = 0

for (const [path, file] of Object.entries(MODELS)) {
  let bytes
  try {
    bytes = readFileSync(file)
  } catch {
    console.error(`missing: ${file}`)
    process.exit(1)
  }
  raw += statSync(file).size
  const ext = path.slice(path.lastIndexOf('.'))
  entries.push(`  ${JSON.stringify(path)}: "data:${MIME[ext]};base64,${bytes.toString('base64')}"`)
}

const out = `// GENERATED by build-models.mjs - do not edit, do not commit.
// The canonical files live in games/hero-moves/assets/; this is only the form
// a published artifact preview is able to serve. See build-models.mjs.
window.__HM_MODELS = {
${entries.join(',\n')}
}
`

const dest = join(HERE, 'assets', 'models.data.js')
writeFileSync(dest, out)
const size = statSync(dest).size
console.log(`${Object.keys(MODELS).length} models, ${(raw / 1e6).toFixed(2)} MB binary -> ${(size / 1e6).toFixed(2)} MB base64`)
console.log(dest)
